version: '3.8'

services:
  app:
    container_name: product-warehouse-app
    env_file:
      - ./.env.docker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT:-3000}:3000'
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: product-warehouse-pg
    env_file:
      - ./.env.docker
    ports:
      - '${DATABASE_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: product-warehouse-pg-admin
    env_file:
      - ./.env.docker
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db

volumes:
  pgdata:
